export enum ErrorCode {
    UNKNOWN = 'UNKNOWN',
    USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    WRONG_CREDENTIALS_EXCEPTION = 'WRONG_CREDENTIALS_EXCEPTION',
    WRONG_AUTHENTICATION_TOKEN_EXCEPTION = 'WRONG AUTHENTICATION TOKEN EXCEPTION',
    OFFERS_NOT_FOUND = "OFFERS_NOT_FOUND"
}
