export type AddOffer  = {
    _offerId: string,
    username: string,
    isPublic: boolean,
    roomLocation: string,
    dateCheckIn: Date,
    dateCheckOut: Date,
    price: number,
    roomPhoto: string,
    paymentMethod: string,
    numberOfGuests: number,
    numberOfBeds: number,
    numberOfGuestsPerBeds: number,
    additionalServices?: Array<string>,
}